/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./../components/AudioPlayer.vue')['default']
    PlaylistDrawer: typeof import('./../components/PlaylistDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/SearchBar.vue')['default']
    SongList: typeof import('./../components/SongList.vue')['default']
    SourceSelector: typeof import('./../components/SourceSelector.vue')['default']
  }
}
